- name : Install MongoDB
  hosts: 127.0.0.1
  tasks:
    - name: Install prerequisites
      command: touch /etc/yum.repos.d/mongodb-org-5.0.repo
      become: yes
    
    - name: Copy mongodb-org-5.o.repo file
      ansible.builtin.copy: 
        dest: /etc/yum.repos.d/mongodb-org-5.0.repo
        state: present

    - name: Install Mongodb package
      ansible.builtin.yum: 
         name: mongodb-org
         state: present
    
    - name: Start MongoDB service
      ansible.builtin.yum:
         name: mongod
         state: started


