- name : Install MongoDB
  hosts: 127.0.0.1
  tasks:
    - name: Install prerequisites
      command: grep ^NAME /etc/passwd

    - name: Install Mongodb package
      ansible.builtin.yum: 
         name: mongodb-org
         state: present
    
    - name: Start MongoDB service
      ansible.builtin.yum:
         name: mongod
         state: started


