- name : Install MongoDB
  hosts: all
  tasks:
    - name: Install prerequisites
      command: touch /etc/yum.repos.d/mongodb-org-5.0.repo
      become: yes
    
    - name: Copy mongodb-org-5.o.repo file
      ansible.builtin.copy: 
        src: mongodb-org-5.0.repo
        dest: /etc/yum.repos.d/mongodb-org-5.0.repo
      become: yes
        

    - name: Install Mongodb package
      ansible.builtin.yum: 
         name: mongodb-org
         state: present
      become: yes
    
    - name: Start MongoDB service
      ansible.builtin.yum:
         name: mongod
         state: present
      become: yes


